FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/web apps/web
COPY packages packages
COPY tsconfig.json .

RUN npm install

WORKDIR /app/apps/web

EXPOSE 5173

CMD ["npm", "run", "dev"]
